#############################################################################
# Makefile for building: BfPlayer
# Generated by qmake (3.1) (Qt 5.15.19)
# Project:  BfPlayer.pro
# Template: app
# Command: D:/workspace/tools/cpp-toolchain/msys64/mingw64/bin/qmake-qt5.exe -o Makefile BfPlayer.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = D:/workspace/tools/cpp-toolchain/msys64/mingw64/bin/qmake-qt5.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = cp -f -R
QINSTALL      = D:/workspace/tools/cpp-toolchain/msys64/mingw64/bin/qmake-qt5.exe -install qinstall
QINSTALL_PROGRAM = D:/workspace/tools/cpp-toolchain/msys64/mingw64/bin/qmake-qt5.exe -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
IDC           = idc
IDL           = widl
ZIP           = 
DEF_FILE      = 
RES_FILE      = BfPlayer_res.o
SED           = sed
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: BfPlayer.pro ../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/win32-g++/qmake.conf ../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/spec_pre.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/qdevice.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/device_config.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/common/sanitize.conf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/common/gcc-base.conf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/common/g++-base.conf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/common/angle.conf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/win32/windows_vulkan_sdk.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/common/windows-vulkan.conf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/common/g++-win32.conf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/common/windows-desktop.conf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/qconfig.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_core.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_network.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/qt_functions.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/qt_config.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/win32-g++/qmake.conf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/exclusive_builds.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/toolchain.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/default_pre.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/win32/default_pre.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/resolve_config.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/exclusive_builds_post.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/default_post.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/precompile_header.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/warn_on.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/qt.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/resources_functions.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/resources.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/moc.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/win32/opengl.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/uic.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/qmake_use.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/file_copies.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/win32/windows.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/testcase_targets.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/exceptions.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/yacc.prf \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/lex.prf \
		BfPlayer.pro \
		../tools/cpp-toolchain/msys64/mingw64/lib/qtmain.prl \
		../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/build_pass.prf \
		BfPlayer.qrc
	$(QMAKE) -o Makefile BfPlayer.pro
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/spec_pre.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/qdevice.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/device_config.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/common/sanitize.conf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/common/gcc-base.conf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/common/g++-base.conf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/common/angle.conf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/win32/windows_vulkan_sdk.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/common/windows-vulkan.conf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/common/g++-win32.conf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/common/windows-desktop.conf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/qconfig.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_concurrent.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_core.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_core_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_dbus.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_gui.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_gui_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_multimedia.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_network.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_network_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_opengl.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_printsupport.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_sql.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_sql_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_testlib.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_widgets.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_xml.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_xml_private.pri:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/qt_functions.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/qt_config.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/win32-g++/qmake.conf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/exclusive_builds.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/toolchain.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/default_pre.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/win32/default_pre.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/resolve_config.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/exclusive_builds_post.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/default_post.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/precompile_header.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/warn_on.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/qt.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/resources_functions.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/resources.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/moc.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/win32/opengl.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/uic.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/qmake_use.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/file_copies.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/win32/windows.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/testcase_targets.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/exceptions.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/yacc.prf:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/lex.prf:
BfPlayer.pro:
../tools/cpp-toolchain/msys64/mingw64/lib/qtmain.prl:
../tools/cpp-toolchain/msys64/mingw64/share/qt5/mkspecs/features/build_pass.prf:
BfPlayer.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile BfPlayer.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
